[package]
org = "ballerina"
name = "auth"
version = "2.4.1"
authors = ["Ballerina"]
keywords = ["security", "authentication", "basic auth"]
repository = "https://github.com/ballerina-platform/module-ballerina-auth"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.2.0"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "auth-native"
version = "2.4.1"
path = "../native/build/libs/auth-native-2.4.1-SNAPSHOT.jar"
